version: "3.4"
services:

  auth_server:
    image: tengelisconsulting/auth_server:latest
    network_mode: "host"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ${PRIV_KEY_FILE}:/app/priv_key
    environment:
      - SERVER_TYPE="auth_server"
      - API_DB_HOST
      - API_DB_PORT
      - AUTH_HOST
      - AUTH_PORT

  api_server:
    image: tengelisconsulting/auth_server:latest
    network_mode: "host"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ${PRIV_KEY_FILE}:/app/priv_key
    environment:
      - SERVER_TYPE="api_server"
      - API_DB_HOST
      - API_DB_PORT
      - AUTH_HOST
      - AUTH_PORT
      - API_PORT

  db:
    image: postgres:12.0-alpine
    network_mode: "host"
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
      - ./_data:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"

  postgrest:
    image: tengelisconsulting/karma_postgrest:latest
    network_mode: "host"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PGHOST
      - PGPORT
      - API_PG_USER
      - API_PG_PASSWORD
      - API_DB_SCHEMA
      - API_ANON_ROLE
      - API_DB_POOL
      - API_DB_POOL_TIMEOUT
      - API_DB_PORT
